# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ma24yh
# "service" is the name of this project. This will also be added to your AWS resource names.
service: notes

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::980826468423:role/test

build:
  external: 
    - aws-sdk

package:
  individually: true

functions:
  getNotes:
    handler: functions/getNotes/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: GET

  addNote:
    handler: functions/addNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: POST

  deleteNote:
    handler: functions/deleteNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: DELETE

  updateNote:
    handler: functions/updateNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: PATCH

  signUp:
    handler: functions/signUp/index.handler
    events:
      - httpApi:
          path: '/api/user/signup'
          method: POST
  login:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: '/api/user/login'
          method: POST

resources:
  Resources:
    notesDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-db
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    usersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-accounts
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
